name: get
on: 
  push:
    branches: 
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: |
        curl https://image.thum.io/get/width/1024/crop/768/https://blog.cyfan.top/ -o blog.cyfan.top.jpg   
        curl https://image.thum.io/get/width/1024/crop/768/https://cyfan.top/ -o cyfan.top.jpg 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./
