name: get
on: 
  push:
    branches: 
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: |
        mkdir download
        cd download
        curl -o '$1.jpg' https://image.thum.io/get/width/1024/crop/768/https://{blog.cyfan.top,cyfan.top}/
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./download
