name: get
on: 
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: 
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: |
        curl https://image.thum.io/get/width/1024/crop/768/https://akilar.top/ -o akilar.top.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://www.boysec.cn/ -o www.boysec.cn.jpg
        curl https://purge.jsdelivr.net/gh/5279314/ScreenShot@gh-pages/*.*
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./
